### ISSUE TITLE
RuntimeError: CUDA error: out of memory

### ISSUE THREAD

**Issue by jasoncow007** [mit-han-lab/nunchaku#144]
self._target(*self._args, **self._kwargs)
  File "D:\ComfyUI-aki-v1.2\main.py", line 175, in prompt_worker
    e.execute(item[2], prompt_id, item[3], item[4])
  File "D:\ComfyUI-aki-v1.2\execution.py", line 531, in execute
    comfy.model_management.unload_all_models()
  File "D:\ComfyUI-aki-v1.2\comfy\model_management.py", line 1214, in unload_all_models
    free_memory(1e30, get_torch_device())
  File "D:\ComfyUI-aki-v1.2\comfy\model_management.py", line 503, in free_memory
    if current_loaded_models[i].model_unload(memory_to_free):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ComfyUI-aki-v1.2\comfy\model_management.py", line 431, in model_unload
    self.model.detach(unpatch_weights)
  File "D:\ComfyUI-aki-v1.2\comfy\model_patcher.py", line 835, in detach
    self.unpatch_model(self.offload_device, unpatch_weights=unpatch_all)
  File "D:\ComfyUI-aki-v1.2\comfy\model_patcher.py", line 734, in unpatch_model
    self.model.to(device_to)
  File "D:\ComfyUI-aki-v1.2\python\Lib\site-packages\torch\nn\modules\module.py", line 1340, in to
    return self._apply(convert)
           ^^^^^^^^^^^^^^^^^^^^
  File "D:\ComfyUI-aki-v1.2\python\Lib\site-packages\torch\nn\modules\module.py", line 900, in _apply
    module._apply(fn)
  File "D:\ComfyUI-aki-v1.2\python\Lib\site-packages\torch\nn\modules\module.py", line 900, in _apply
    module._apply(fn)
  File "D:\ComfyUI-aki-v1.2\python\Lib\site-packages\torch\nn\modules\module.py", line 927, in _apply
    param_applied = fn(param)
                    ^^^^^^^^^
  File "D:\ComfyUI-aki-v1.2\python\Lib\site-packages\torch\nn\modules\module.py", line 1326, in convert
    return t.to(
           ^^^^^
RuntimeError: CUDA error: out of memory
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

**Comment by edisonchan** [comment]
What is your configure?

**Comment by jasoncow007** [comment]
> What is your configure?

cp311+torch2.5+cuda12.4，16gvram+64gram

**Comment by botnang** [comment]
same here， ubuntu 22.04, cp311+torch2.6+cuda12.4，16gvram+256gram

**Comment by lmxyy** [comment]
> > What is your configure?
> 
> cp311+torch2.5+cuda12.4，16gvram+64gram

To fit the model within 16GB of VRAM, a 4-bit text encoder is required. You need to install `deepcompressor` to enable it:
```shell
pip install poetry
git clone https://github.com/mit-han-lab/deepcompressor
cd deepcompressor
poetry install
```
This dependency will be removed in v0.1.4, which will be released this Thursday or Friday. I will let you know then.

**Comment by lmxyy** [comment]
v0.1.4 was released. You can use our 4-bit text encoder or CPU offloading to reduce the memory usage.
I will close this issue. Feel free to open new ones if you have questions!

**Comment by jasoncow007** [comment]
> v0.1.4 was released. You can use our 4-bit text encoder or CPU offloading to reduce the memory usage.
> I will close this issue. Feel free to open new ones if you have questions!

need recompile?

**Comment by lmxyy** [comment]
@jasoncow007 Yeah. I will continue building the windows wheels to avoid recompiling.

**Comment by jasoncow007** [comment]
> [@jasoncow007](https://github.com/jasoncow007) Yeah. I will continue building the windows wheels to avoid recompiling.

thanks for your job, looking forward to it

**Comment by KLL535** [comment]
What are these warnings? The compilation process simply freezes on them.

```
cl : Command line warning D9025 : overriding '/D__CUDA_NO_HALF_OPERATORS__' with '/U__CUDA_NO_HALF_OPERATORS__'
  cl : Command line warning D9025 : overriding '/D__CUDA_NO_HALF_CONVERSIONS__' with '/U__CUDA_NO_HALF_CONVERSIONS__'
  cl : Command line warning D9025 : overriding '/D__CUDA_NO_HALF2_OPERATORS__' with '/U__CUDA_NO_HALF2_OPERATORS__'
  cl : Command line warning D9025 : overriding '/D__CUDA_NO_BFLOAT16_CONVERSIONS__' with '/U__CUDA_NO_BFLOAT16_CONVERSIONS__'
  gemm_w4a4_launch_bf16.cu
  H:\ComfyUI128\python_embeded\temp\nunchaku\third_party\spdlog\include\spdlog\fmt\bundled\format.h(3273): warning #27-D: character value is out of range
      return U"\x9999999a\x828f5c29\x80418938\x80068db9\x8000a7c6\x800010c7"
               ^

  Remark: The warnings can be suppressed with "-diag-suppress <warning-number>"

  H:\ComfyUI128\python_embeded\temp\nunchaku\third_party\spdlog\include\spdlog\fmt\bundled\format.h(3273): warning #27-D: character value is out of range
      return U"\x9999999a\x828f5c29\x80418938\x80068db9\x8000a7c6\x800010c7"
                         ^

  H:\ComfyUI128\python_embeded\temp\nunchaku\third_party\spdlog\include\spdlog\fmt\bundled\format.h(3273): warning #27-D: character value is out of range
      return U"\x9999999a\x828f5c29\x80418938\x80068db9\x8000a7c6\x800010c7"
                                   ^

  H:\ComfyUI128\python_embeded\temp\nunchaku\third_party\spdlog\include\spdlog\fmt\bundled\format.h(3273): warning #27-D: character value is out of range
      return U"\x9999999a\x828f5c29\x80418938\x80068db9\x8000a7c6\x800010c7"
                                             ^

  H:\ComfyUI128\python_embeded\temp\nunchaku\third_party\spdlog\include\spdlog\fmt\bundled\format.h(3273): warning #27-D: character value is out of range
      return U"\x9999999a\x828f5c29\x80418938\x80068db9\x8000a7c6\x800010c7"
                                                       ^

  H:\ComfyUI128\python_embeded\temp\nunchaku\third_party\spdlog\include\spdlog\fmt\bundled\format.h(3273): warning #27-D: character value is out of range
      return U"\x9999999a\x828f5c29\x80418938\x80068db9\x8000a7c6\x800010c7"
                                                                 ^

  H:\ComfyUI128\python_embeded\temp\nunchaku\third_party\spdlog\include\spdlog\fmt\bundled\format.h(3274): warning #27-D: character value is out of range
             U"\x800001ae\x8000002b"[index];
               ^

  H:\ComfyUI128\python_embeded\temp\nunchaku\third_party\spdlog\include\spdlog\fmt\bundled\format.h(3274): warning #27-D: character value is out of range
             U"\x800001ae\x8000002b"[index];
                         ^

  C:\Program Files (x86)\Windows Kits\10\include\10.0.20348.0\um\winnt.h(24245): warning #174-D: expression has no effect
        (CallbackEnviron);
        ^

  C:\Program Files (x86)\Windows Kits\10\include\10.0.20348.0\um\winuser.h(14631): warning #108-D: signed bit field of length 1
        BOOL fBarFocused:1;
             ^

  C:\Program Files (x86)\Windows Kits\10\include\10.0.20348.0\um\winuser.h(14632): warning #108-D: signed bit field of length 1
        BOOL fFocused:1;
             ^
```

**Comment by mantou77278** [comment]
I have same here,Ubuntu22.04,NVIDIA GeForce RTX 4060 Ti) Memory: 15956.625 MiB 32G RAM
got prompt
Requested to load FluxClipModel_
loaded completely 9.5367431640625e+25 9319.23095703125 True
CLIP/text encoder model load device: cuda:0, offload device: cpu, current: cuda:0, dtype: torch.float16
clip missing: ['text_projection.weight']
clip missing: ['encoder.block.0.layer.0.SelfAttention.q.weight', 'encoder.block.0.layer.0.SelfAttention.k.weight', 'encoder.block.0.layer.0.SelfAttention.v.weight', 'encoder.block.0.layer.0.SelfAttention.o.weight', 'encoder.block.0.layer.1.DenseReluDense.wi_0.weight', 'encoder.block.0.layer.1.DenseReluDense.wi_1.weight', 'encoder.block.0.layer.1.DenseReluDense.wo.weight', 'encoder.block.1.layer.0.SelfAttention.q.weight', 'encoder.block.1.layer.0.SelfAttention.k.weight', 'encoder.block.1.layer.0.SelfAttention.v.weight', 'encoder.block.1.layer.0.SelfAttention.o.weight', 'encoder.block.1.layer.1.DenseReluDense.wi_0.weight', 'encoder.block.1.layer.1.DenseReluDense.wi_1.weight', 'encoder.block.1.layer.1.DenseReluDense.wo.weight', 'encoder.block.2.layer.0.SelfAttention.q.weight', 'encoder.block.2.layer.0.SelfAttention.k.weight', 'encoder.block.2.layer.0.SelfAttention.v.weight', 'encoder.block.2.layer.0.SelfAttention.o.weight', 'encoder.block.2.layer.1.DenseReluDense.wi_0.weight', 'encoder.block.2.layer.1.DenseReluDense.wi_1.weight', 'encoder.block.2.layer.1.DenseReluDense.wo.weight', 'encoder.block.3.layer.0.SelfAttention.q.weight', 'encoder.block.3.layer.0.SelfAttention.k.weight', 'encoder.block.3.layer.0.SelfAttention.v.weight', 'encoder.block.3.layer.0.SelfAttention.o.weight', 'encoder.block.3.layer.1.DenseReluDense.wi_0.weight', 'encoder.block.3.layer.1.DenseReluDense.wi_1.weight', 'encoder.block.3.layer.1.DenseReluDense.wo.weight', 'encoder.block.4.layer.0.SelfAttention.q.weight', 'encoder.block.4.layer.0.SelfAttention.k.weight', 'encoder.block.4.layer.0.SelfAttention.v.weight', 'encoder.block.4.layer.0.SelfAttention.o.weight', 'encoder.block.4.layer.1.DenseReluDense.wi_0.weight', 'encoder.block.4.layer.1.DenseReluDense.wi_1.weight', 'encoder.block.4.layer.1.DenseReluDense.wo.weight', 'encoder.block.5.layer.0.SelfAttention.q.weight', 'encoder.block.5.layer.0.SelfAttention.k.weight', 'encoder.block.5.layer.0.SelfAttention.v.weight', 'encoder.block.5.layer.0.SelfAttention.o.weight', 'encoder.block.5.layer.1.DenseReluDense.wi_0.weight', 'encoder.block.5.layer.1.DenseReluDense.wi_1.weight', 'encoder.block.5.layer.1.DenseReluDense.wo.weight', 'encoder.block.6.layer.0.SelfAttention.q.weight', 'encoder.block.6.layer.0.SelfAttention.k.weight', 'encoder.block.6.layer.0.SelfAttention.v.weight', 'encoder.block.6.layer.0.SelfAttention.o.weight', 'encoder.block.6.layer.1.DenseReluDense.wi_0.weight', 'encoder.block.6.layer.1.DenseReluDense.wi_1.weight', 'encoder.block.6.layer.1.DenseReluDense.wo.weight', 'encoder.block.7.layer.0.SelfAttention.q.weight', 'encoder.block.7.layer.0.SelfAttention.k.weight', 'encoder.block.7.layer.0.SelfAttention.v.weight', 'encoder.block.7.layer.0.SelfAttention.o.weight', 'encoder.block.7.layer.1.DenseReluDense.wi_0.weight', 'encoder.block.7.layer.1.DenseReluDense.wi_1.weight', 'encoder.block.7.layer.1.DenseReluDense.wo.weight', 'encoder.block.8.layer.0.SelfAttention.q.weight', 'encoder.block.8.layer.0.SelfAttention.k.weight', 'encoder.block.8.layer.0.SelfAttention.v.weight', 'encoder.block.8.layer.0.SelfAttention.o.weight', 'encoder.block.8.layer.1.DenseReluDense.wi_0.weight', 'encoder.block.8.layer.1.DenseReluDense.wi_1.weight', 'encoder.block.8.layer.1.DenseReluDense.wo.weight', 'encoder.block.9.layer.0.SelfAttention.q.weight', 'encoder.block.9.layer.0.SelfAttention.k.weight', 'encoder.block.9.layer.0.SelfAttention.v.weight', 'encoder.block.9.layer.0.SelfAttention.o.weight', 'encoder.block.9.layer.1.DenseReluDense.wi_0.weight', 'encoder.block.9.layer.1.DenseReluDense.wi_1.weight', 'encoder.block.9.layer.1.DenseReluDense.wo.weight', 'encoder.block.10.layer.0.SelfAttention.q.weight', 'encoder.block.10.layer.0.SelfAttention.k.weight', 'encoder.block.10.layer.0.SelfAttention.v.weight', 'encoder.block.10.layer.0.SelfAttention.o.weight', 'encoder.block.10.layer.1.DenseReluDense.wi_0.weight', 'encoder.block.10.layer.1.DenseReluDense.wi_1.weight', 'encoder.block.10.layer.1.DenseReluDense.wo.weight', 'encoder.block.11.layer.0.SelfAttention.q.weight', 'encoder.block.11.layer.0.SelfAttention.k.weight', 'encoder.block.11.layer.0.SelfAttention.v.weight', 'encoder.block.11.layer.0.SelfAttention.o.weight', 'encoder.block.11.layer.1.DenseReluDense.wi_0.weight', 'encoder.block.11.layer.1.DenseReluDense.wi_1.weight', 'encoder.block.11.layer.1.DenseReluDense.wo.weight', 'encoder.block.12.layer.0.SelfAttention.q.weight', 'encoder.block.12.layer.0.SelfAttention.k.weight', 'encoder.block.12.layer.0.SelfAttention.v.weight', 'encoder.block.12.layer.0.SelfAttention.o.weight', 'encoder.block.12.layer.1.DenseReluDense.wi_0.weight', 'encoder.block.12.layer.1.DenseReluDense.wi_1.weight', 'encoder.block.12.layer.1.DenseReluDense.wo.weight', 'encoder.block.13.layer.0.SelfAttention.q.weight', 'encoder.block.13.layer.0.SelfAttention.k.weight', 'encoder.block.13.layer.0.SelfAttention.v.weight', 'encoder.block.13.layer.0.SelfAttention.o.weight', 'encoder.block.13.layer.1.DenseReluDense.wi_0.weight', 'encoder.block.13.layer.1.DenseReluDense.wi_1.weight', 'encoder.block.13.layer.1.DenseReluDense.wo.weight', 'encoder.block.14.layer.0.SelfAttention.q.weight', 'encoder.block.14.layer.0.SelfAttention.k.weight', 'encoder.block.14.layer.0.SelfAttention.v.weight', 'encoder.block.14.layer.0.SelfAttention.o.weight', 'encoder.block.14.layer.1.DenseReluDense.wi_0.weight', 'encoder.block.14.layer.1.DenseReluDense.wi_1.weight', 'encoder.block.14.layer.1.DenseReluDense.wo.weight', 'encoder.block.15.layer.0.SelfAttention.q.weight', 'encoder.block.15.layer.0.SelfAttention.k.weight', 'encoder.block.15.layer.0.SelfAttention.v.weight', 'encoder.block.15.layer.0.SelfAttention.o.weight', 'encoder.block.15.layer.1.DenseReluDense.wi_0.weight', 'encoder.block.15.layer.1.DenseReluDense.wi_1.weight', 'encoder.block.15.layer.1.DenseReluDense.wo.weight', 'encoder.block.16.layer.0.SelfAttention.q.weight', 'encoder.block.16.layer.0.SelfAttention.k.weight', 'encoder.block.16.layer.0.SelfAttention.v.weight', 'encoder.block.16.layer.0.SelfAttention.o.weight', 'encoder.block.16.layer.1.DenseReluDense.wi_0.weight', 'encoder.block.16.layer.1.DenseReluDense.wi_1.weight', 'encoder.block.16.layer.1.DenseReluDense.wo.weight', 'encoder.block.17.layer.0.SelfAttention.q.weight', 'encoder.block.17.layer.0.SelfAttention.k.weight', 'encoder.block.17.layer.0.SelfAttention.v.weight', 'encoder.block.17.layer.0.SelfAttention.o.weight', 'encoder.block.17.layer.1.DenseReluDense.wi_0.weight', 'encoder.block.17.layer.1.DenseReluDense.wi_1.weight', 'encoder.block.17.layer.1.DenseReluDense.wo.weight', 'encoder.block.18.layer.0.SelfAttention.q.weight', 'encoder.block.18.layer.0.SelfAttention.k.weight', 'encoder.block.18.layer.0.SelfAttention.v.weight', 'encoder.block.18.layer.0.SelfAttention.o.weight', 'encoder.block.18.layer.1.DenseReluDense.wi_0.weight', 'encoder.block.18.layer.1.DenseReluDense.wi_1.weight', 'encoder.block.18.layer.1.DenseReluDense.wo.weight', 'encoder.block.19.layer.0.SelfAttention.q.weight', 'encoder.block.19.layer.0.SelfAttention.k.weight', 'encoder.block.19.layer.0.SelfAttention.v.weight', 'encoder.block.19.layer.0.SelfAttention.o.weight', 'encoder.block.19.layer.1.DenseReluDense.wi_0.weight', 'encoder.block.19.layer.1.DenseReluDense.wi_1.weight', 'encoder.block.19.layer.1.DenseReluDense.wo.weight', 'encoder.block.20.layer.0.SelfAttention.q.weight', 'encoder.block.20.layer.0.SelfAttention.k.weight', 'encoder.block.20.layer.0.SelfAttention.v.weight', 'encoder.block.20.layer.0.SelfAttention.o.weight', 'encoder.block.20.layer.1.DenseReluDense.wi_0.weight', 'encoder.block.20.layer.1.DenseReluDense.wi_1.weight', 'encoder.block.20.layer.1.DenseReluDense.wo.weight', 'encoder.block.21.layer.0.SelfAttention.q.weight', 'encoder.block.21.layer.0.SelfAttention.k.weight', 'encoder.block.21.layer.0.SelfAttention.v.weight', 'encoder.block.21.layer.0.SelfAttention.o.weight', 'encoder.block.21.layer.1.DenseReluDense.wi_0.weight', 'encoder.block.21.layer.1.DenseReluDense.wi_1.weight', 'encoder.block.21.layer.1.DenseReluDense.wo.weight', 'encoder.block.22.layer.0.SelfAttention.q.weight', 'encoder.block.22.layer.0.SelfAttention.k.weight', 'encoder.block.22.layer.0.SelfAttention.v.weight', 'encoder.block.22.layer.0.SelfAttention.o.weight', 'encoder.block.22.layer.1.DenseReluDense.wi_0.weight', 'encoder.block.22.layer.1.DenseReluDense.wi_1.weight', 'encoder.block.22.layer.1.DenseReluDense.wo.weight', 'encoder.block.23.layer.0.SelfAttention.q.weight', 'encoder.block.23.layer.0.SelfAttention.k.weight', 'encoder.block.23.layer.0.SelfAttention.v.weight', 'encoder.block.23.layer.0.SelfAttention.o.weight', 'encoder.block.23.layer.1.DenseReluDense.wi_0.weight', 'encoder.block.23.layer.1.DenseReluDense.wi_1.weight', 'encoder.block.23.layer.1.DenseReluDense.wo.weight']
Requested to load AutoencodingEngine
loaded completely 1643.7768478393555 159.87335777282715 True
GPU 0 (NVIDIA GeForce RTX 4060 Ti) Memory: 15956.625 MiB
VRAM > 14GiB，disable CPU offload
[2025-06-05 06:05:18.123] [info] Initializing QuantizedFluxModel on device 0
!!! Exception during processing !!! CUDA error: out of memory (at /nunchaku/src/Tensor.h:95)
Traceback (most recent call last):
  File "/home/bruce-ko/ComfyUI/execution.py", line 349, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
  File "/home/bruce-ko/ComfyUI/execution.py", line 224, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
  File "/home/bruce-ko/ComfyUI/execution.py", line 196, in _map_node_over_list
    process_inputs(input_dict, i)
  File "/home/bruce-ko/ComfyUI/execution.py", line 185, in process_inputs
    results.append(getattr(obj, func)(**inputs))
  File "/home/bruce-ko/ComfyUI/custom_nodes/ComfyUI-nunchaku/nodes/models/flux.py", line 343, in load_model
    self.transformer, self.metadata = NunchakuFluxTransformer2dModel.from_pretrained(
  File "/home/bruce-ko/miniconda3/envs/comfyui/lib/python3.10/site-packages/huggingface_hub/utils/_validators.py", line 114, in _inner_fn
    return fn(*args, **kwargs)
  File "/home/bruce-ko/miniconda3/envs/comfyui/lib/python3.10/site-packages/nunchaku/models/transformers/transformer_flux.py", line 379, in from_pretrained
    m = load_quantized_module(
  File "/home/bruce-ko/miniconda3/envs/comfyui/lib/python3.10/site-packages/nunchaku/models/transformers/transformer_flux.py", line 275, in load_quantized_module
    m.init(use_fp4, offload, bf16, 0 if device.index is None else device.index)
RuntimeError: CUDA error: out of memory (at /nunchaku/src/Tensor.h:95)

Prompt executed in 2.28 seconds

**Comment by mantou77278** [comment]
I have resolved the issue，clip load use cpu.

**Comment by zlchs131QQ** [comment]
> I have resolved the issue，clip load use cpu.

you are such a genius
