### ISSUE TITLE
RuntimeError: CUDA error: operation not supported

### ISSUE THREAD

**Issue by StartHua** [mit-han-lab/nunchaku#183]
[2025-03-10 12:51:47.723] [info] Initializing QuantizedFluxModel
[2025-03-10 12:51:47.761] [info] Loading weights from E:\Comfyui\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\models\diffusion_models\mit-han-lab/svdq-int4-flux.1-dev\transformer_blocks.safetensors
[2025-03-10 12:51:47.764] [warning] Failed to load safetensors using method MIO: CUDA error: operation not supported (at E:\comfyui\nunchaku0.1.4\nunchaku\src\Serialization.cpp:130)
[2025-03-10 12:51:54.705] [info] Done.
!!! Exception during processing !!! CUDA error: operation not supported
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

Traceback (most recent call last):
  File "E:\Comfyui\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\execution.py", line 327, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Comfyui\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\execution.py", line 202, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Comfyui\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\execution.py", line 174, in _map_node_over_list
    process_inputs(input_dict, i)
  File "E:\Comfyui\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\execution.py", line 163, in process_inputs
    results.append(getattr(obj, func)(**inputs))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Comfyui\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\custom_nodes\svdquant\nodes\models\flux.py", line 158, in load_model
    transformer = transformer.to(device)
                  ^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Comfyui\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\python_embeded\Lib\site-packages\diffusers\models\modeling_utils.py", line 1077, in to
    return super().to(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Comfyui\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\python_embeded\Lib\site-packages\torch\nn\modules\module.py", line 1343, in to
    return self._apply(convert)
           ^^^^^^^^^^^^^^^^^^^^
  File "E:\Comfyui\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\python_embeded\Lib\site-packages\torch\nn\modules\module.py", line 903, in _apply
    module._apply(fn)
  File "E:\Comfyui\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\python_embeded\Lib\site-packages\torch\nn\modules\module.py", line 903, in _apply
    module._apply(fn)
  File "E:\Comfyui\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\python_embeded\Lib\site-packages\torch\nn\modules\module.py", line 903, in _apply
    module._apply(fn)
  File "E:\Comfyui\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\python_embeded\Lib\site-packages\torch\nn\modules\module.py", line 930, in _apply
    param_applied = fn(param)
                    ^^^^^^^^^
  File "E:\Comfyui\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\python_embeded\Lib\site-packages\torch\nn\modules\module.py", line 1329, in convert
    return t.to(
           ^^^^^
RuntimeError: CUDA error: operation not supported
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

**Comment by lmxyy** [comment]
Could you provide more details? What system are you using? Which wheel did you use? What is your GPU and how much VRAM and RAM do you have?

**Comment by StartHua** [comment]
![Image](https://github.com/user-attachments/assets/f87ea7b1-058c-40aa-9145-751d141305cf) 

![Image](https://github.com/user-attachments/assets/8f47cd75-48b4-4703-bd06-09936ae10c63)

**Comment by StartHua** [comment]
已经解决了：编译问题

**Comment by tl2012tl** [comment]
> 已经解决了：编译问题

我也是这个问题,请问怎么解决的?

**Comment by lmxyy** [comment]
Hi! Could you please try our latest Nunchaku v0.2.0 release? You can also try our prebuilt wheels, available for both Windows and Linux, with support for Python 3.10–3.13 and PyTorch 2.5–2.8. You can download them from any of the following sources:
* [Hugging Face](https://huggingface.co/mit-han-lab/nunchaku/tree/main)
* [ModelScope](https://modelscope.cn/models/Lmxyy1999/nunchaku)
* [GitHub Releases](https://github.com/mit-han-lab/nunchaku/releases)

Also, make sure to upgrade [ComfyUI-nunchaku](https://github.com/mit-han-lab/ComfyUI-nunchaku) to v0.2.0 for full compatibility.

Let us know if you run into any issues!

**Comment by 1612655140** [comment]
> 已经解决了：编译问题

怎么解决的
