### ISSUE TITLE
[Bug] CUDA out of memory (flux demo app) - 12GB GPU

### ISSUE THREAD

**Issue by andchir** [mit-han-lab/nunchaku#473]
### Checklist

- [x] 1. I have searched for related issues and FAQs (https://github.com/mit-han-lab/nunchaku/blob/main/docs/faq.md) but was unable to find a solution.
- [x] 2. The issue persists in the latest version.
- [x] 3. Please note that without environment information and a minimal reproducible example, it will be difficult for us to reproduce and address the issue, which may delay our response.
- [x] 4. If your report is a question rather than a bug, please submit it as a discussion at https://github.com/mit-han-lab/nunchaku/discussions/new/choose. Otherwise, this issue will be closed.
- [x] 5. If this is related to ComfyUI, please report it at https://github.com/mit-han-lab/ComfyUI-nunchaku/issues.
- [x] 6. I will do my best to describe the issue in English.

### Describe the Bug

nunchaku  0.3.1+torch2.7

I run the demo application like this:
~~~
cd app/flux.1/t2i
python run_gradio.py --use-qencoder --no-safety-checker --model dev
or
python run_gradio.py --use-qencoder --no-safety-checker --model schnell
~~~

I have a 12GB GPU.

I get an error:
~~~
torch.OutOfMemoryError: CUDA out of memory. Tried to allocate 512.00 MiB. GPU 0 has a total capacity of 11.59 GiB of which 521.62 MiB is free. Including non-PyTorch memory, this process has 10.28 GiB memory in use.
~~~

But I remember that on the previous version 2.x I could use the demo without this problem. What has changed in the demo? Can you add optimization for 12GB GPU?

### Environment

Ubuntu 24.04, torch==2.7.0, CUDA 12.0 or CUDA 12.8

### Reproduction Steps

~~~
cd app/flux.1/t2i
python run_gradio.py --use-qencoder --no-safety-checker --model dev
or
python run_gradio.py --use-qencoder --no-safety-checker --model schnell
~~~

**Comment by lmxyy** [comment]
Should be runnable. Let me take a look.

**Comment by lmxyy** [comment]
It works well on my side. The max GPU memory usage is about 11G.

**Comment by andchir** [comment]
@lmxyy
Thank you for your quick reply! I will check again tomorrow and let you know. But it is strange that the example with Pulid works for me on 12 GB GPU.

**Comment by andchir** [comment]
I don't know what the reason is, but I can't even run an example "examples/flux.1-dev-qencoder.py".

nvidia-smi shows before launch: 549MiB /  12282MiB

Log:
~~~
python examples/flux.1-dev-qencoder.py
[2025-06-17 16:27:31.374] [info] Initializing QuantizedFluxModel on device 0
[2025-06-17 16:27:31.486] [info] Loading partial weights from pytorch
[2025-06-17 16:27:32.302] [info] Done.
Injecting quantized module
Couldn't connect to the Hub: (ProtocolError('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer')), '(Request ID: 50bc6628-6c51-49f7-8548-59f3e4cf34da)').
Will try to load from local cache.
Loading pipeline components...:   0%|                                                 | 0/7 [00:00<?, ?it/s]You set `add_prefix_space`. The tokenizer needs to be converted from the slow tokenizers
Loading pipeline components...: 100%|█████████████████████████████████████████| 7/7 [00:00<00:00,  8.47it/s]
100%|███████████████████████████████████████████████████████████████████████| 50/50 [00:23<00:00,  2.10it/s]
Traceback (most recent call last):
  File "/path/to/nunchaku/examples/flux.1-dev-qencoder.py", line 18, in <module>
    image = pipeline("A cat holding a sign that says hello world", num_inference_steps=50, guidance_scale=3.5).images[0]
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/path/to/nunchaku/venv/lib/python3.12/site-packages/torch/utils/_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/path/to/nunchaku/venv/lib/python3.12/site-packages/diffusers/pipelines/flux/pipeline_flux.py", line 980, in __call__
    image = self.vae.decode(latents, return_dict=False)[0]
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/path/to/nunchaku/venv/lib/python3.12/site-packages/diffusers/utils/accelerate_utils.py", line 46, in wrapper
    return method(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/path/to/nunchaku/venv/lib/python3.12/site-packages/diffusers/models/autoencoders/autoencoder_kl.py", line 323, in decode
    decoded = self._decode(z).sample
              ^^^^^^^^^^^^^^^
  File "/path/to/nunchaku/venv/lib/python3.12/site-packages/diffusers/models/autoencoders/autoencoder_kl.py", line 294, in _decode
    dec = self.decoder(z)
          ^^^^^^^^^^^^^^^
  File "/path/to/nunchaku/venv/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1751, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/path/to/nunchaku/venv/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1762, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/path/to/nunchaku/venv/lib/python3.12/site-packages/diffusers/models/autoencoders/vae.py", line 305, in forward
    sample = up_block(sample, latent_embeds)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/path/to/nunchaku/venv/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1751, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/path/to/nunchaku/venv/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1762, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/path/to/nunchaku/venv/lib/python3.12/site-packages/diffusers/models/unets/unet_2d_blocks.py", line 2643, in forward
    hidden_states = upsampler(hidden_states)
                    ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/path/to/nunchaku/venv/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1751, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/path/to/nunchaku/venv/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1762, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/path/to/nunchaku/venv/lib/python3.12/site-packages/diffusers/models/upsampling.py", line 188, in forward
    hidden_states = self.conv(hidden_states)
                    ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/path/to/nunchaku/venv/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1751, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/path/to/nunchaku/venv/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1762, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/path/to/nunchaku/venv/lib/python3.12/site-packages/torch/nn/modules/conv.py", line 554, in forward
    return self._conv_forward(input, self.weight, self.bias)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/path/to/nunchaku/venv/lib/python3.12/site-packages/torch/nn/modules/conv.py", line 549, in _conv_forward
    return F.conv2d(
           ^^^^^^^^^
torch.OutOfMemoryError: CUDA out of memory. Tried to allocate 512.00 MiB. GPU 0 has a total capacity of 11.59 GiB of which 252.81 MiB is free. Including non-PyTorch memory, this process has 10.80 GiB memory in use. Of the allocated memory 3.95 GiB is allocated by PyTorch, and 391.67 MiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True to avoid fragmentation.  See documentation for Memory Management  (https://pytorch.org/docs/stable/notes/cuda.html#environment-variables)
~~~

**Comment by nitinmukesh** [comment]
@andchir 

Wanna try this
https://github.com/newgenai79/sd-diffuser-webui

Refer SVDQuant / Nunchaku tab and see if it is working. I am using it on 8 GB VRAM + 16 GB RAM setup and it takes 4-8 GB VRAM depending on model. Also support all performance optimizations.

![Image](https://github.com/user-attachments/assets/0a1283ef-54f8-42a8-bfc1-de4a0402d106)

**Comment by andchir** [comment]
@nitinmukesh 
Thanks for your tip! It works for me.

**Comment by nitinmukesh** [comment]
@andchir 

Awesome. Thanks for confirmation.
Did you need to fix any package from requirements.txt? I have Windows so I can't test on Linux.

**Comment by andchir** [comment]
@nitinmukesh 
No, everything was installed very simply.
The only thing is that I used Python3.12, so I changed the whl URL to install via pip.

**Comment by nitinmukesh** [comment]
Cool thanks.
