### ISSUE TITLE
Unable to pin memory: operation not supported

### ISSUE THREAD

**Issue by booksword** [mit-han-lab/nunchaku#49]
(venv) ubuntu@hp:~/nunchaku$ ls
app  assets  build  comfyui  example.py  LICENCE.txt  MANIFEST.in  nunchaku  nunchaku.egg-info  pyproject.toml  README.md  schnell.model  setup.py  src  third_party
(venv) ubuntu@hp:~/nunchaku$ python example.py
[2024-12-10 10:42:02.110] [info] Initializing QuantizedFluxModel
[2024-12-10 10:42:02.243] [info] Loading weights from /home/ubuntu/.cache/huggingface/hub/models--mit-han-lab--svdq-int4-flux.1-schnell/snapshots/3957d6ece9852f09ccadc064f1fd25964394a490/transformer_blocks.safetensors
[2024-12-10 10:42:02.243] [warning] Unable to pin memory: operation not supported
[2024-12-10 10:42:02.243] [info] Try MAP_PRIVATE
Traceback (most recent call last):
  File "/home/ubuntu/nunchaku/example.py", line 5, in <module>
    transformer = NunchakuFluxTransformer2dModel.from_pretrained("mit-han-lab/svdq-int4-flux.1-schnell")
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/ComfyUI/venv/lib/python3.12/site-packages/huggingface_hub/utils/_validators.py", line 114, in _inner_fn
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/nunchaku/nunchaku/models/transformer_flux.py", line 206, in from_pretrained
    m = load_quantized_module(transformer_block_path, device=device)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/nunchaku/nunchaku/models/transformer_flux.py", line 114, in load_quantized_module
    m.load(path)
RuntimeError: CUDA error: invalid argument (at /home/ubuntu/nunchaku/src/Serialization.cpp:101)
(venv) ubuntu@hp:~/nunchaku$ nvidia-smi
Tue Dec 10 10:42:14 2024
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 565.57.01              Driver Version: 565.57.01      CUDA Version: 12.7     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  NVIDIA GeForce RTX 4060        Off |   00000000:01:00.0 Off |                  N/A |
| 33%   32C    P8             N/A /  115W |       2MiB /   8188MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+------------------------+----------------------+

+-----------------------------------------------------------------------------------------+
| Processes:                                                                              |
|  GPU   GI   CI        PID   Type   Process name                              GPU Memory |
|        ID   ID                                                               Usage      |
|=========================================================================================|
|  No running processes found                                                             |
+-----------------------------------------------------------------------------------------+
(venv) ubuntu@hp:~/nunchaku$

**Comment by booksword** [comment]
not support 4060 :(

**Comment by lmxyy** [comment]
4060 was supported. However, since it only has 8G GPU memory, it may require some offloading.

**Comment by wardensc2** [comment]
My 3090 get this warning too:

![image](https://github.com/user-attachments/assets/cc2052b7-3a21-4e5f-9729-ca21e958bca1)

**Comment by iiiian** [comment]
my 4060ti 16GB is having the same issue.

**Comment by vbqgyy** [comment]
WIN10 3090  64gRAM comfyui having the same issue. torch2.4.1+cu124 ，already installed cuda12.6

**Comment by GGGHSL** [comment]
@booksword hi, have you fixed this alreay? I got the same problem and now fixed it. could you try `ldd _C.so` and see if there is  any 'not found' in the output

**Comment by hdfhssg** [comment]
my 3080l 16GB is having the same issue.

**Comment by LiJT** [comment]
4090 also have this issue, torch2.6+cu126

**Comment by jackyzhangjun** [comment]
4060Ti 16G  python 3.10.11 torch 2.5.2+ cu124 一样的问题 same issue   Unable to pin memory: operation not supported

**Comment by lmxyy** [comment]
I will test it. Did you install the package via wheels? Have you tried building from source?

**Comment by jackyzhangjun** [comment]
I install it via wheels~

**Comment by HyperTwo** [comment]
rtx 3080, python 3.10.9  torch 2.6.0+ cu126, same problem, I built from source successfully and follow the installation instruction

**Comment by jackyzhangjun** [comment]
nunchaku-0.1.2-cp310-cp310-win_amd64.whl   I use this to continue，the installation is quite all right ，but the workflow gets。。。collapsed·~with Unable to pin memory

**Comment by shofans** [comment]
3090 win10， 3.11 torch 2.4.1+ cu12.4,tried building from source，and Using  nunchaku-0.1.2 wheels 3.10 torch 2.4.1+ cu12.4\3.11 torch 2.5.1+ cu12.4 ，and Using  nunchaku-0.1.3 wheels 3.10 torch 2.4.1+ cu12.4\3.11 torch 2.5.1+ cu12.4 \3.12 torch 2.6.0+ cu126 ,Installation everything is ok，but all runs to "load flux dit" encountering issue:Compiling nunchaku fails in all of the following environments，comfyui latest version

**Comment by LiJT** [comment]
same here in both any configuration
pytorch version: 2.6.0+cu126
Set vram state to: NORMAL_VRAM
Device: cuda:0 NVIDIA GeForce RTX 4090 : cudaMallocAsync
Using pytorch attention
ComfyUI version: 0.3.19

![Image](https://github.com/user-attachments/assets/9b826e4d-34c5-4ee4-889d-f82fce3c0bda)

```
got prompt
Using pytorch attention in VAE
Using pytorch attention in VAE
VAE load device: cuda:0, offload device: cpu, dtype: torch.bfloat16
[2025-03-04 22:25:23.288] [info] Initializing QuantizedFluxModel
[2025-03-04 22:25:23.321] [info] Loading weights from E:\ComfyUI_windows_portable\ComfyUI\models\diffusion_models\svdq-int4-flux.1-dev\transformer_blocks.safetensors
[2025-03-04 22:25:23.321] [warning] Unable to pin memory: operation not supported
[2025-03-04 22:25:28.221] [info] Done.

E:\ComfyUI_windows_portable>pause
```

Maybe the problem caused by Windows?

**Comment by judian17** [comment]
@LiJT 

![Image](https://github.com/user-attachments/assets/434b8bba-a221-49f8-8198-b5ade65a78ab)

![Image](https://github.com/user-attachments/assets/f1b46add-615b-4430-b13e-8734ec6e7c93) I'm sorry if this is a basic question, but if your device number is 0, should this device ID also be set to 0?

**Comment by hdfhssg** [comment]
> 我的 3080L 16GB 遇到了同样的问题。在以下所有环境中编译双节棍都失败：torch 2.6+cu126、torch 2.6+cu128 和 torch 2.5.1+cu124。

I have solved the issue and can now run flux-int4, but flux-fp4 still has the same problem.

**Comment by hdfhssg** [comment]
> > > 我的 3080L 16GB 遇到了同样的问题。在以下所有环境中编译双节棍都失败：torch 2.6+cu126、torch 2.6+cu128 和 torch 2.5.1+cu124。
> > 
> > 
> > 我的系统是 Windows 10。我已经解决了这个问题，现在可以运行 flux-int4，但 flux-fp4 仍然存在同样的问题。
> 
> 您使用什么 GPU？NVFP4 仅在 50 系列 GPU 上受支持。

Okay, my GPU is a 3080 Laptop.

**Comment by judian17** [comment]
@hdfhssg How did you solve the problem of "Unable to pin memory: operation not supported"? I've found that other people have the same problem

**Comment by hdfhssg** [comment]
> [@hdfhssg](https://github.com/hdfhssg) How did you solve the problem of "Unable to pin memory: operation not supported"? I've found that other people have the same problem

I referred to the location mentioned by @GGGHSL, but after modifying it according to their method, I couldn't build it. This might be because their system is not Windows. So, I made my own modifications and successfully got it running. But I still appreciate @GGGHSL for pointing out the relevant code section.

**Comment by judian17** [comment]
@LiJT @jackyzhangjun @HyperTwo Could you tell me whether you're using Windows 10 or Windows 11? Currently, I've only found success stories from Windows 11 users, while the failure cases are all from Windows 10. I'm in the process of collecting more data to verify this.

**Comment by HyperTwo** [comment]
> [@LiJT](https://github.com/LiJT) [@jackyzhangjun](https://github.com/jackyzhangjun) [@HyperTwo](https://github.com/HyperTwo) Could you tell me whether you're using Windows 10 or Windows 11? Currently, I've only found success stories from Windows 11 users, while the failure cases are all from Windows 10. I'm in the process of collecting more data to verify this.

Thanks for your reply, my system is win10, python 3.10.9, torch2.6.0+cu12.6 ,gpu is rtx3080 10G
I noticed the problem that caused “Unable to pin memory” perhaps referring to the "nunchaku/src/Serialization.cpp" file? It seems that the “cudaHostRegisterReadOnly” process failed? Is there a compatibility issue during memory alignment?

**Comment by hdfhssg** [comment]
> [@LiJT](https://github.com/LiJT) [@jackyzhangjun](https://github.com/jackyzhangjun) [@HyperTwo](https://github.com/HyperTwo) Could you tell me whether you're using Windows 10 or Windows 11? Currently, I've only found success stories from Windows 11 users, while the failure cases are all from Windows 10. I'm in the process of collecting more data to verify this.

@LiJT @jackyzhangjun @HyperTwo .I have successfully built the .whl file. If you're facing this issue, you can use it.

🤗 Hugging Face link: https://huggingface.co/hdfhssg/torch-2.6.0-cu128/tree/main

📺 Bilibili link: https://www.bilibili.com/video/BV1up9ZYQERM?vd_source=05f663ef9a1ecb6e0836fc2568e9de79

**Comment by HyperTwo** [comment]
> > [@LiJT](https://github.com/LiJT) [@jackyzhangjun](https://github.com/jackyzhangjun) [@HyperTwo](https://github.com/HyperTwo) Could you tell me whether you're using Windows 10 or Windows 11? Currently, I've only found success stories from Windows 11 users, while the failure cases are all from Windows 10. I'm in the process of collecting more data to verify this.
> 
> [@LiJT](https://github.com/LiJT) [@jackyzhangjun](https://github.com/jackyzhangjun) [@HyperTwo](https://github.com/HyperTwo) .I have successfully built the .whl file. If you're facing this issue, you can use it.
> 
> 🤗 Hugging Face link: https://huggingface.co/hdfhssg/torch-2.6.0-cu128/tree/main
> 
> 📺 Bilibili link: https://www.bilibili.com/video/BV1up9ZYQERM?vd_source=05f663ef9a1ecb6e0836fc2568e9de79

It's work~~ good job, 看来确实是Serialization.cpp文件的锁定内存操作导致的

**Comment by judian17** [comment]
> > [@LiJT](https://github.com/LiJT) [@jackyzhangjun](https://github.com/jackyzhangjun) [@HyperTwo](https://github.com/HyperTwo) Could you tell me whether you're using Windows 10 or Windows 11? Currently, I've only found success stories from Windows 11 users, while the failure cases are all from Windows 10. I'm in the process of collecting more data to verify this.
> 
> [@LiJT](https://github.com/LiJT) [@jackyzhangjun](https://github.com/jackyzhangjun) [@HyperTwo](https://github.com/HyperTwo) .I have successfully built the .whl file. If you're facing this issue, you can use it.
> 
> 🤗 Hugging Face link: https://huggingface.co/hdfhssg/torch-2.6.0-cu128/tree/main
> 
> 📺 Bilibili link: https://www.bilibili.com/video/BV1up9ZYQERM?vd_source=05f663ef9a1ecb6e0836fc2568e9de79

It works! Thank you!

**Comment by lmxyy** [comment]
This issue should be fixed in v0.1.4. If it still persists, feel free to open new issues!
